version: "3.0"
services:
  db:
    container_name: psql_lt
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'